version: "3.5"

services:
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmqdata:/var/lib/rabbitmq/mnesia